kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-view
  labels:
    app: dev-sample-view
spec:
  selector:
    matchLabels:
      deployment: dev-sample-view
  template:
    metadata:
      labels:
        deployment: dev-sample-view
        app: dev-sample-view
    spec:
      containers:
        - name: sample-view
          image: image-registry.openshift-image-registry.svc:5000/crt-default-ini-dev/sample-view:3a7ed9d5334724d519ac47792dfca3b117a7d431
          env:
            - name: API_BASE_URL
              value: https://dev-sample-app-crt-default-ini-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
